import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateQuizQuestionsTable1783499100000 implements MigrationInterface {
  name = 'CreateQuizQuestionsTable1783499100000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "quiz_questions" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "public_id" uuid NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "body" text NOT NULL,
        "correct_answers" jsonb NOT NULL DEFAULT '[]',
        "published" boolean NOT NULL DEFAULT false,
        "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        CONSTRAINT "PK_quiz_questions" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_quiz_questions_public_id" UNIQUE ("public_id")
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_quiz_questions_created_at" ON "quiz_questions" ("created_at")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_quiz_questions_published" ON "quiz_questions" ("published")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "quiz_questions"`);
  }
}
