import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateQuizPairGameTables1783499200000 implements MigrationInterface {
  name = 'CreateQuizPairGameTables1783499200000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "quiz_pairs" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "public_id" uuid NOT NULL,
        "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
        "first_player_user_id" bigint NOT NULL,
        "second_player_user_id" bigint,
        "status" character varying NOT NULL DEFAULT 'PendingSecondPlayer',
        "start_game_date" TIMESTAMPTZ,
        "finish_game_date" TIMESTAMPTZ,
        "first_player_score" integer,
        "second_player_score" integer,
        "first_player_finished_at" TIMESTAMPTZ,
        "second_player_finished_at" TIMESTAMPTZ,
        CONSTRAINT "PK_quiz_pairs" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_quiz_pairs_public_id" UNIQUE ("public_id")
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_quiz_pairs_status" ON "quiz_pairs" ("status")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_quiz_pairs_first_player_user_id" ON "quiz_pairs" ("first_player_user_id")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_quiz_pairs_second_player_user_id" ON "quiz_pairs" ("second_player_user_id")
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_quiz_pairs_pending_matchmaking" ON "quiz_pairs" ("status")
      WHERE "status" = 'PendingSecondPlayer'
    `);

    await queryRunner.query(`
      CREATE TABLE "quiz_pair_questions" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "pair_id" bigint NOT NULL,
        "question_id" bigint NOT NULL,
        "order" smallint NOT NULL,
        CONSTRAINT "PK_quiz_pair_questions" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_quiz_pair_questions_pair_order" UNIQUE ("pair_id", "order")
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_quiz_pair_questions_pair_id" ON "quiz_pair_questions" ("pair_id")
    `);

    await queryRunner.query(`
      CREATE TABLE "quiz_pair_answers" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "pair_id" bigint NOT NULL,
        "user_id" bigint NOT NULL,
        "question_id" bigint NOT NULL,
        "answer" character varying NOT NULL,
        "is_correct" boolean NOT NULL,
        "answered_at" TIMESTAMPTZ NOT NULL,
        CONSTRAINT "PK_quiz_pair_answers" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_quiz_pair_answers_pair_user_question" UNIQUE ("pair_id", "user_id", "question_id")
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "IDX_quiz_pair_answers_pair_id" ON "quiz_pair_answers" ("pair_id")
    `);

    await queryRunner.query(`
      ALTER TABLE "quiz_pairs"
      ADD CONSTRAINT "FK_quiz_pairs_first_player_user_id"
      FOREIGN KEY ("first_player_user_id") REFERENCES "users"("id") ON DELETE RESTRICT
    `);

    await queryRunner.query(`
      ALTER TABLE "quiz_pairs"
      ADD CONSTRAINT "FK_quiz_pairs_second_player_user_id"
      FOREIGN KEY ("second_player_user_id") REFERENCES "users"("id") ON DELETE RESTRICT
    `);

    await queryRunner.query(`
      ALTER TABLE "quiz_pair_questions"
      ADD CONSTRAINT "FK_quiz_pair_questions_pair_id"
      FOREIGN KEY ("pair_id") REFERENCES "quiz_pairs"("id") ON DELETE CASCADE
    `);

    await queryRunner.query(`
      ALTER TABLE "quiz_pair_questions"
      ADD CONSTRAINT "FK_quiz_pair_questions_question_id"
      FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id") ON DELETE RESTRICT
    `);

    await queryRunner.query(`
      ALTER TABLE "quiz_pair_answers"
      ADD CONSTRAINT "FK_quiz_pair_answers_pair_id"
      FOREIGN KEY ("pair_id") REFERENCES "quiz_pairs"("id") ON DELETE CASCADE
    `);

    await queryRunner.query(`
      ALTER TABLE "quiz_pair_answers"
      ADD CONSTRAINT "FK_quiz_pair_answers_user_id"
      FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT
    `);

    await queryRunner.query(`
      ALTER TABLE "quiz_pair_answers"
      ADD CONSTRAINT "FK_quiz_pair_answers_question_id"
      FOREIGN KEY ("question_id") REFERENCES "quiz_questions"("id") ON DELETE RESTRICT
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "quiz_pair_answers" DROP CONSTRAINT "FK_quiz_pair_answers_question_id"
    `);
    await queryRunner.query(`
      ALTER TABLE "quiz_pair_answers" DROP CONSTRAINT "FK_quiz_pair_answers_user_id"
    `);
    await queryRunner.query(`
      ALTER TABLE "quiz_pair_answers" DROP CONSTRAINT "FK_quiz_pair_answers_pair_id"
    `);
    await queryRunner.query(`
      ALTER TABLE "quiz_pair_questions" DROP CONSTRAINT "FK_quiz_pair_questions_question_id"
    `);
    await queryRunner.query(`
      ALTER TABLE "quiz_pair_questions" DROP CONSTRAINT "FK_quiz_pair_questions_pair_id"
    `);
    await queryRunner.query(`
      ALTER TABLE "quiz_pairs" DROP CONSTRAINT "FK_quiz_pairs_second_player_user_id"
    `);
    await queryRunner.query(`
      ALTER TABLE "quiz_pairs" DROP CONSTRAINT "FK_quiz_pairs_first_player_user_id"
    `);
    await queryRunner.query(`DROP TABLE "quiz_pair_answers"`);
    await queryRunner.query(`DROP TABLE "quiz_pair_questions"`);
    await queryRunner.query(`DROP TABLE "quiz_pairs"`);
  }
}
